sudo: required
services:
  - docker

before_install:
  - docker build -t johnlorac/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run johnlorac/react-test npm test -- --coverage

after_success:
  - docker build -t johnlorac/multi-client ./client
  - docker build -t johnlorac/multi-nginx ./nginx
  - docker build -t johnlorac/multi-server ./server
  - docker build -t johnlorac/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push johnlorac/multi-client
  - docker push johnlorac/multi-nginx
  - docker push johnlorac/multi-server
  - docker push johnlorac/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-103099220287
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY